### ISSUE TITLE
Crashed when -t 1 in ubuntu

### ISSUE THREAD

**Issue by byzhang** [byzhang/nxweb#4]
Here is the statck

```
#0 0x00007f8cfdf14cc9 in GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1 0x00007f8cfdf180d8 in __GI_abort () at abort.c:89
#2 0x00007f8cfdf0db86 in __assert_fail_base (fmt=0x7f8cfe05e830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7f8cfe914015 "sub->pub==pub",
file=file@entry=0x7f8cfe913e70 "/home/byzhang/src/nxweb/src/lib/nx_event.c", line=line@entry=457, function=function@entry=0x7f8cfe914190 <__PRETTY_FUNCTION.4618> "nxe_unsubscribe") at assert.c:92
#3 0x00007f8cfdf0dc32 in GI___assert_fail (assertion=0x7f8cfe914015 "sub->pub==pub", file=0x7f8cfe913e70 "/home/byzhang/src/nxweb/src/lib/nx_event.c", line=457, function=0x7f8cfe914190 <__PRETTY_FUNCTION.4618> "nxe_unsubscribe")
at assert.c:101
#4 0x00007f8cfe8fee69 in nxe_unsubscribe (pub=0xaa1, sub=0xb15dc0) at /home/byzhang/src/nxweb/src/lib/nx_event.c:457
#5 0x00007f8cfe8f9ea2 in nxd_http_proxy_pool_finalize (pp=0xb15d88) at /home/byzhang/src/nxweb/src/lib/nxd_http_proxy.c:206
#6 0x00007f8cfe8ed208 in on_net_thread_shutdown (sub=0xb15760, pub=0xb15500, data=...) at /home/byzhang/src/nxweb/src/lib/http_server.c:718
#7 0x00007f8cfe8fed01 in message_event_deliver (evt=0x7f8cf8000c50) at /home/byzhang/src/nxweb/src/lib/nx_event.c:421
#8 0x00007f8cfe8fe067 in nxe_process_loop (loop=0x7f8cf80008c0) at /home/byzhang/src/nxweb/src/lib/nx_event.c:163
#9 0x00007f8cfe8fe133 in nxe_run (loop=0x7f8cf80008c0) at /home/byzhang/src/nxweb/src/lib/nx_event.c:191
#10 0x00007f8cfe8ed9f0 in net_thread_main (ptr=0xb154d0) at /home/byzhang/src/nxweb/src/lib/http_server.c:869
#11 0x00007f8cfe6c8182 in start_thread (arg=0x7f8cfdcd1700) at pthread_create.c:312
#12 0x00007f8cfdfd847d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

CentOS is free.

**Comment by lyxm** [comment]
so you run "prod" on ubuntu?

**Comment by byzhang** [comment]
yes.

Thanks,
-B
